### ISSUE TITLE
Cannot read file from repository

### ISSUE THREAD

**Issue by litefeel** [game-ci/unity-test-runner#111] opened 2021-04-01 18:37 UTC
Hi.

![image](https://user-images.githubusercontent.com/1288575/113338499-c74dbe00-935b-11eb-85b8-920031ec3204.png)

https://github.com/litefeel/Unity-RenameTools/runs/2248431732?check_suite_focus=true

the file of `UnityLicense/2019.4.20f1.ulf` in repository.

**Comment by webbertakken** [comment] 2021-04-02 10:05
This literally means that the file is not there in the docker container. Note that only [some paths](https://github.com/game-ci/unity-test-runner/blob/main/src/model/docker.js) are mounted in the container.

**Comment by litefeel** [comment] 2021-04-02 16:14
Fix it https://github.com/game-ci/unity-test-runner/pull/112

**Comment by pixelpax** [comment] 2021-07-06 23:03
If not what litefeel proposed, @webbertakken , what's the correct solution to this problem? This is preventing my team from using game-ci, unfortunately. Thanks for your help and for maintaining this awesome project.

**Comment by webbertakken** [comment] 2021-07-06 23:31
The recommended and [documented](https://game.ci/docs/github/getting-started) way is to copy the contents of your license file into the `UNITY_LICENSE` variable.

Note that since we've started GameCI, I've not heard a any remotely convincing arguments as to why you would push around the license as a file. But if you must, then the path obviously has to be one of the paths that is mounted into the container.

We're open for merge requests if you feel test-runner is lacking in a way. However it should not break existing workflows, like the one above does.

**Comment by litefeel** [comment] 2021-07-07 03:32
@pixelpax
Now, github action can store multiline strings to GITHUB_ENV, So you can use the  `UNITY_LICENSE` variable.
like this.
~~~
# Set env
- name: Set env UNITY_LICENSE_FILE
  run: |
     echo 'UNITY_LICENSE<<EOF' >> $GITHUB_ENV
     cat UnityLicense/${{ matrix.unityVersion }}.ulf >> $GITHUB_ENV
     echo '' >> $GITHUB_ENV
     echo 'EOF' >> $GITHUB_ENV
~~~

https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#multiline-strings

**Comment by webbertakken** [comment] 2021-07-07 08:24
While that would work, this is a workaround that makes setting up your workflow much harder. 

We might also be able to help others if one or both of you could explain why the regular way doesn't work for you, and maybe also what didn't work about passing the file and providing a path to that.

**Comment by pixelpax** [comment] 2021-07-07 21:14
Ah, thank you for your help, both of you!  I agree it would it would be preferred to use string file contents froma github secret. Unfortunately when I try to use github secrets they come out as empty strings.

I can't come up with a good reason for spending anyone's energy supporting files except for github secrets misbehaving. Even this is resolvable by just putting the file contents in as a multiline string just as well.

**Comment by pixelpax** [comment] 2021-07-07 21:28
When I've worked with secrets before they usually show up as **** if present
![image](https://user-images.githubusercontent.com/1467013/124830884-21a08100-df40-11eb-8af7-c88470d84ed1.png)
![image](https://user-images.githubusercontent.com/1467013/124830978-409f1300-df40-11eb-948c-9e5a7f7a82fd.png)

**Comment by webbertakken** [comment] 2021-07-07 23:16
Note that hundreds of people were successful getting it to work following our documentation at [game.ci](https://game.ci).
Also note that it's intended behaviour that your secrets don't show up in your logs, they're supposed to show up as `***`.

If you have found an actual bug in GitHub secrets, it would be very important to report this to GitHub.
That said, in my experience secrets have been working perfectly fine all the time.

**Comment by pixelpax** [comment] 2021-07-08 01:37
Thank you for your help and patience, I'm 99% sure it's something incorrectly configured, but I'm struggling to debug. I will ask more in discord if I still can't figure it out.

**Comment by davidmfinol** [comment] 2021-08-03 22:56
@pixelpax did you find out what was wrong?

**Comment by pixelpax** [comment] 2021-08-14 03:40
I was using an .alf where a .ulf was supposed to go, I believe. Still not sure why gh secrets weren't populating.

**Comment by davidmfinol** [comment] 2021-08-23 05:34
Ok, closing this issue since this doesn't seem to be an issue with Unity Test Runner.

**Closed by davidmfinol** 2021-08-23 05:34 UTC
Labels: question
