### ISSUE TITLE
Unity no longer supports manual activation of Personal licenses

### ISSUE THREAD

**Issue by poi-vrc** [game-ci/unity-test-runner#235] opened 2023-08-11 16:16 UTC
My builds starting from few hours ago keep failing because of licensing issues. After some investigation and found out this in 
https://license.unity3d.com/manual :

> Unity no longer supports manual activation of Personal licenses. For more information, see: https://docs.unity3d.com/Manual/LicensesAndActivation.html

Does it mean we no longer can use CI for Unity builds without a Professional license anymore? 😱

**Comment by webbertakken** [comment] 2023-08-11 23:30
There's a thread going on about this on our discord: https://discord.com/channels/710946343828455455/1138586951604248666

**Comment by GabLeRoux** [comment] 2023-09-07 01:26
Closing as duplicate of https://github.com/game-ci/documentation/issues/408

Feel free to continue discussion in other issue 👍

**Closed by GabLeRoux** 2023-09-07 01:26 UTC

**Comment by pridroid** [comment] 2026-02-12 06:13
How do I get access to the discord channel?  and the thread?

**Comment by GabLeRoux** [comment] 2026-02-12 13:51
> How do I get access to the discord channel? and the thread?

https://game.ci/discord :+1:

**Comment by cgbeaulieu** [comment] 2026-04-29 00:53
Confirmed the workaround above still works today.
